server:
  port: 9001

  datasource:
    url: jdbc:mysql:///hrm-system?useSSL=false&useUicode=true&characterEncoding=UTF-8

# swagger 自动配置
hrm:
  swagger:
    title: "系统管理服务"
    description: "系统管理服务接口文档"
